-- Enable RLS
alter table auth.users enable row level security;

-- PROFILES TABLE
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  role text default 'creator' check (role in ('admin', 'creator')),
  avatar_url text,
  streak_count int default 0,
  streak_points int default 0,
  longest_streak int default 0,
  x_id text,
  x_username text,
  x_avatar text,
  x_followers_count int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- TASKS TABLE (Admin Created)
create table public.tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  project_name text not null,
  description text,
  reward text,
  deadline timestamp with time zone,
  status text default 'Open' check (status in ('Open', 'Active', 'Completed', 'Paused')),
  category text,
  image_url text,
  participants_count int default 0,
  created_by uuid references public.profiles(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.tasks enable row level security;

create policy "Tasks are viewable by everyone."
  on tasks for select
  using ( true );

create policy "Admins can insert tasks."
  on tasks for insert
  with check ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

create policy "Admins can update tasks."
  on tasks for update
  using ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

-- SUBMISSIONS TABLE (Creator Work)
create table public.submissions (
  id bigint generated by default as identity primary key,
  task_id bigint references public.tasks(id) not null,
  creator_id uuid references public.profiles(id) not null,
  submission_link text not null,
  status text default 'Pending' check (status in ('Pending', 'Verified', 'Rejected')),
  submitted_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.submissions enable row level security;

create policy "Creators can view their own submissions."
  on submissions for select
  using ( auth.uid() = creator_id );

create policy "Admins can view all submissions."
  on submissions for select
  using ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

create policy "Creators can insert submissions."
  on submissions for insert
  with check ( auth.uid() = creator_id );

-- TRIGGERS
-- Handle new user creation (auto-create profile)
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', 'creator');
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
